<?php /* BeginFeature:Station */
/**
 * This is the model base class for the table "station".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Station".
 *
 * Columns in table "station" available as properties of the model,
 * followed by relations of table "station" available as properties of the model.
 *
 * @property integer $id    
 * BeginFeature:City    
 * @property integer $id_city
 * EndFeature:City    
 * BeginFeature:VehicleType    
 * @property integer $id_vehicle_type
 * EndFeature:VehicleType    
 * @property string $name    
 *
 * BeginFeature:Line
 * @property Line[] $lines
 * EndFeature:Line
 * BeginFeature:Line
 * @property Line[] $lines1
 * EndFeature:Line
 * BeginFeature:Segment
 * @property Segment[] $segments
 * EndFeature:Segment
 * BeginFeature:Segment
 * @property Segment[] $segments1
 * EndFeature:Segment
 * BeginFeature:City
 * @property City $idCity
 * EndFeature:City
 * BeginFeature:VehicleType
 * @property VehicleType $idVehicleType
 * EndFeature:VehicleType
 * BeginFeature:Ticket
 * @property Ticket[] $tickets
 * EndFeature:Ticket
 * BeginFeature:Ticket
 * @property Ticket[] $tickets1
 * EndFeature:Ticket
 */
abstract class BaseStation extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'station';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Station|Stations', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array(
			/* BeginFeature:City */
			'id_city, '.
			/* EndFeature:City */
			
			/* BeginFeature:VehicleType */
			'id_vehicle_type, '.
			/* EndFeature:VehicleType */
			'name', 'required'),
			array(
			/* BeginFeature:City */
			'id_city, '.
			/* EndFeature:City */
			/* BeginFeature:VehicleType */
			'id_vehicle_type, '.
			/* EndFeature:VehicleType */                            
			'', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>45),
			array('id, '.
			/* BeginFeature:City */
			'id_city, '.
			/* EndFeature:City */
			
			/* BeginFeature:VehicleType */
			'id_vehicle_type, '.
			/* EndFeature:VehicleType */
			'name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
            		/* BeginFeature:Line */
			'lines' => array(self::HAS_MANY, 'Line', 'id_station_arrival'),
            		/* EndFeature:Line */
            		/* BeginFeature:Line */
			'lines1' => array(self::HAS_MANY, 'Line', 'id_station_departure'),
            		/* EndFeature:Line */
            		/* BeginFeature:Segment */
			'segments' => array(self::HAS_MANY, 'Segment', 'id_station_arrival'),
            		/* EndFeature:Segment */
            		/* BeginFeature:Segment */
			'segments1' => array(self::HAS_MANY, 'Segment', 'id_station_departure'),
            		/* EndFeature:Segment */
            		/* BeginFeature:City */
			'idCity' => array(self::BELONGS_TO, 'City', 'id_city'),
            		/* EndFeature:City */
            		/* BeginFeature:VehicleType */
			'idVehicleType' => array(self::BELONGS_TO, 'VehicleType', 'id_vehicle_type'),
            		/* EndFeature:VehicleType */
            		/* BeginFeature:Ticket */
			'tickets' => array(self::HAS_MANY, 'Ticket', 'id_station_arrival'),
            		/* EndFeature:Ticket */
            		/* BeginFeature:Ticket */
			'tickets1' => array(self::HAS_MANY, 'Ticket', 'id_station_departure'),
            		/* EndFeature:Ticket */
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			/* BeginFeature:City */
			'id_city' => null,
			/* EndFeature:City */
			/* BeginFeature:VehicleType */
			'id_vehicle_type' => null,
			/* EndFeature:VehicleType */
			'name' => Yii::t('app', 'Name'),
			/* BeginFeature:Line */
			'lines' => null,
			/* EndFeature:Line */
			/* BeginFeature:Line */
			'lines1' => null,
			/* EndFeature:Line */
			/* BeginFeature:Segment */
			'segments' => null,
			/* EndFeature:Segment */
			/* BeginFeature:Segment */
			'segments1' => null,
			/* EndFeature:Segment */
			/* BeginFeature:City */
			'idCity' => null,
			/* EndFeature:City */
			/* BeginFeature:VehicleType */
			'idVehicleType' => null,
			/* EndFeature:VehicleType */
			/* BeginFeature:Ticket */
			'tickets' => null,
			/* EndFeature:Ticket */
			/* BeginFeature:Ticket */
			'tickets1' => null,
			/* EndFeature:Ticket */
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		/* BeginFeature:City */
		$criteria->compare('id_city', $this->id_city);
		/* EndFeature:City */
		/* BeginFeature:VehicleType */
		$criteria->compare('id_vehicle_type', $this->id_vehicle_type);
		/* EndFeature:VehicleType */
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
/* EndFeature:Station */