<?php /* BeginFeature:Luggage */
/**
 * This is the model base class for the table "luggage".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Luggage".
 *
 * Columns in table "luggage" available as properties of the model,
 * followed by relations of table "luggage" available as properties of the model.
 *
 * @property integer $id    
 * BeginFeature:Ticket    
 * @property integer $id_ticket
 * EndFeature:Ticket    
 * @property integer $code    
 * @property string $description    
 * @property integer $weight    
 * @property integer $special    
 * @property integer $animal    
 * @property integer $music_instrument    
 * @property integer $out_of_dimensions    
 *
 * BeginFeature:Ticket
 * @property Ticket $idTicket
 * EndFeature:Ticket
 */
abstract class BaseLuggage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'luggage';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Luggage|Luggages', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array(
			/* BeginFeature:Ticket */
			'id_ticket, '.
			/* EndFeature:Ticket */
			'code, description', 'required'),
			array(
			/* BeginFeature:Ticket */
			'id_ticket, '.
			/* EndFeature:Ticket */
			'code, weight, special, animal, music_instrument, out_of_dimensions', 'numerical', 'integerOnly'=>true),
			array('description', 'length', 'max'=>45),
			array('weight, special, animal, music_instrument, out_of_dimensions', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, '.
			/* BeginFeature:Ticket */
			'id_ticket, '.
			/* EndFeature:Ticket */
			'code, description, weight, special, animal, music_instrument, out_of_dimensions', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
            		/* BeginFeature:Ticket */
			'idTicket' => array(self::BELONGS_TO, 'Ticket', 'id_ticket'),
            		/* EndFeature:Ticket */
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			/* BeginFeature:Ticket */
			'id_ticket' => null,
			/* EndFeature:Ticket */
			'code' => Yii::t('app', 'Code'),
			'description' => Yii::t('app', 'Description'),
			'weight' => Yii::t('app', 'Weight'),
			'special' => Yii::t('app', 'Special'),
			'animal' => Yii::t('app', 'Animal'),
			'music_instrument' => Yii::t('app', 'Music Instrument'),
			'out_of_dimensions' => Yii::t('app', 'Out Of Dimensions'),
			/* BeginFeature:Ticket */
			'idTicket' => null,
			/* EndFeature:Ticket */
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		/* BeginFeature:Ticket */
		$criteria->compare('id_ticket', $this->id_ticket);
		/* EndFeature:Ticket */
		$criteria->compare('code', $this->code);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('weight', $this->weight);
		$criteria->compare('special', $this->special);
		$criteria->compare('animal', $this->animal);
		$criteria->compare('music_instrument', $this->music_instrument);
		$criteria->compare('out_of_dimensions', $this->out_of_dimensions);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
/* EndFeature:Luggage */