<?php /* BeginFeature:VehicleSeat */
/**
 * This is the model base class for the table "vehicle_seat".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VehicleSeat".
 *
 * Columns in table "vehicle_seat" available as properties of the model,
 * followed by relations of table "vehicle_seat" available as properties of the model.
 *
 * @property integer $id    
 * BeginFeature:Vehicle    
 * @property integer $id_vehicle
 * EndFeature:Vehicle    
 * BeginFeature:SeatType    
 * @property integer $id_seat_type
 * EndFeature:SeatType    
 * @property string $code    
 * @property integer $position    
 * @property string $description    
 *
 * BeginFeature:TicketSegment
 * @property TicketSegment[] $ticketSegments
 * EndFeature:TicketSegment
 * BeginFeature:SeatType
 * @property SeatType $idSeatType
 * EndFeature:SeatType
 * BeginFeature:Vehicle
 * @property Vehicle $idVehicle
 * EndFeature:Vehicle
 */
abstract class BaseVehicleSeat extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vehicle_seat';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Vehicle Seat|Vehicle Seats', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array(
			/* BeginFeature:Vehicle */
			'id_vehicle, '.
			/* EndFeature:Vehicle */
			
			/* BeginFeature:SeatType */
			'id_seat_type, '.
			/* EndFeature:SeatType */
			'code, position', 'required'),
			array(
			/* BeginFeature:Vehicle */
			'id_vehicle, '.
			/* EndFeature:Vehicle */
			
			/* BeginFeature:SeatType */
			'id_seat_type, '.
			/* EndFeature:SeatType */
			'position', 'numerical', 'integerOnly'=>true),
			array('code, description', 'length', 'max'=>45),
			array('description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, '.
			/* BeginFeature:Vehicle */
			'id_vehicle, '.
			/* EndFeature:Vehicle */
			
			/* BeginFeature:SeatType */
			'id_seat_type, '.
			/* EndFeature:SeatType */
			'code, position, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
            		/* BeginFeature:TicketSegment */
			'ticketSegments' => array(self::HAS_MANY, 'TicketSegment', 'id_vehicle_seat'),
            		/* EndFeature:TicketSegment */
            		/* BeginFeature:SeatType */
			'idSeatType' => array(self::BELONGS_TO, 'SeatType', 'id_seat_type'),
            		/* EndFeature:SeatType */
            		/* BeginFeature:Vehicle */
			'idVehicle' => array(self::BELONGS_TO, 'Vehicle', 'id_vehicle'),
            		/* EndFeature:Vehicle */
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			/* BeginFeature:Vehicle */
			'id_vehicle' => null,
			/* EndFeature:Vehicle */
			/* BeginFeature:SeatType */
			'id_seat_type' => null,
			/* EndFeature:SeatType */
			'code' => Yii::t('app', 'Code'),
			'position' => Yii::t('app', 'Position'),
			'description' => Yii::t('app', 'Description'),
			/* BeginFeature:TicketSegment */
			'ticketSegments' => null,
			/* EndFeature:TicketSegment */
			/* BeginFeature:SeatType */
			'idSeatType' => null,
			/* EndFeature:SeatType */
			/* BeginFeature:Vehicle */
			'idVehicle' => null,
			/* EndFeature:Vehicle */
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		/* BeginFeature:Vehicle */
		$criteria->compare('id_vehicle', $this->id_vehicle);
		/* EndFeature:Vehicle */
		/* BeginFeature:SeatType */
		$criteria->compare('id_seat_type', $this->id_seat_type);
		/* EndFeature:SeatType */
		$criteria->compare('code', $this->code, true);
		$criteria->compare('position', $this->position);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
/* EndFeature:VehicleSeat */