<?php /* BeginFeature:DocumentType */
/**
 * This is the model base class for the table "document_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DocumentType".
 *
 * Columns in table "document_type" available as properties of the model,
 * followed by relations of table "document_type" available as properties of the model.
 *
 * @property integer $id_document_type    
 * @property string $name    
 *
 * BeginFeature:Passenger
 * @property Passenger[] $passengers
 * EndFeature:Passenger
 */
abstract class BaseDocumentType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'document_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Document Type|Document Types', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>45),
			array('id_document_type, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
            		/* BeginFeature:Passenger */
			'passengers' => array(self::HAS_MANY, 'Passenger', 'id_document_type'),
            		/* EndFeature:Passenger */
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_document_type' => Yii::t('app', 'Id Document Type'),
			'name' => Yii::t('app', 'Name'),
			/* BeginFeature:Passenger */
			'passengers' => null,
			/* EndFeature:Passenger */
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_document_type', $this->id_document_type);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
/* EndFeature:DocumentType */