<?php /* BeginFeature:TicketSegment */
/**
 * This is the model base class for the table "ticket_segment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TicketSegment".
 *
 * Columns in table "ticket_segment" available as properties of the model,
 * followed by relations of table "ticket_segment" available as properties of the model.
 *
 * @property integer $id    
 * BeginFeature:Ticket    
 * @property integer $id_ticket
 * EndFeature:Ticket    
 * BeginFeature:Segment    
 * @property integer $id_segment
 * EndFeature:Segment    
 * BeginFeature:VehicleSeat    
 * @property integer $id_vehicle_seat
 * EndFeature:VehicleSeat    
 *
 * BeginFeature:Segment
 * @property Segment $idSegment
 * EndFeature:Segment
 * BeginFeature:Ticket
 * @property Ticket $idTicket
 * EndFeature:Ticket
 * BeginFeature:VehicleSeat
 * @property VehicleSeat $idVehicleSeat
 * EndFeature:VehicleSeat
 */
abstract class BaseTicketSegment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ticket_segment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Ticket Segment|Ticket Segments', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array(
			/* BeginFeature:Ticket */
			'id_ticket, '.
			/* EndFeature:Ticket */
			'id_segment', 'required'),
			array(
			/* BeginFeature:Ticket */
			'id_ticket, '.
			/* EndFeature:Ticket */
			
			/* BeginFeature:Segment */
			'id_segment, '.
			/* EndFeature:Segment */
			'id_vehicle_seat', 'numerical', 'integerOnly'=>true),
			array('id_vehicle_seat', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, '.
			/* BeginFeature:Ticket */
			'id_ticket, '.
			/* EndFeature:Ticket */
			
			/* BeginFeature:Segment */
			'id_segment, '.
			/* EndFeature:Segment */
			'id_vehicle_seat', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
            		/* BeginFeature:Segment */
			'idSegment' => array(self::BELONGS_TO, 'Segment', 'id_segment'),
            		/* EndFeature:Segment */
            		/* BeginFeature:Ticket */
			'idTicket' => array(self::BELONGS_TO, 'Ticket', 'id_ticket'),
            		/* EndFeature:Ticket */
            		/* BeginFeature:VehicleSeat */
			'idVehicleSeat' => array(self::BELONGS_TO, 'VehicleSeat', 'id_vehicle_seat'),
            		/* EndFeature:VehicleSeat */
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			/* BeginFeature:Ticket */
			'id_ticket' => null,
			/* EndFeature:Ticket */
			/* BeginFeature:Segment */
			'id_segment' => null,
			/* EndFeature:Segment */
			/* BeginFeature:VehicleSeat */
			'id_vehicle_seat' => null,
			/* EndFeature:VehicleSeat */
			/* BeginFeature:Segment */
			'idSegment' => null,
			/* EndFeature:Segment */
			/* BeginFeature:Ticket */
			'idTicket' => null,
			/* EndFeature:Ticket */
			/* BeginFeature:VehicleSeat */
			'idVehicleSeat' => null,
			/* EndFeature:VehicleSeat */
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		/* BeginFeature:Ticket */
		$criteria->compare('id_ticket', $this->id_ticket);
		/* EndFeature:Ticket */
		/* BeginFeature:Segment */
		$criteria->compare('id_segment', $this->id_segment);
		/* EndFeature:Segment */
		/* BeginFeature:VehicleSeat */
		$criteria->compare('id_vehicle_seat', $this->id_vehicle_seat);
		/* EndFeature:VehicleSeat */

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
/* EndFeature:TicketSegment */