<?php /* BeginFeature:Travel */
/**
 * This is the model base class for the table "travel".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Travel".
 *
 * Columns in table "travel" available as properties of the model,
 * followed by relations of table "travel" available as properties of the model.
 *
 * @property integer $id    
 * BeginFeature:Line    
 * @property integer $id_line
 * EndFeature:Line    
 * BeginFeature:Vehicle    
 * @property integer $id_vehicle
 * EndFeature:Vehicle    
 * @property string $start_date    
 * @property string $end_date    
 *
 * BeginFeature:FlightPlan
 * @property FlightPlan[] $flightPlans
 * EndFeature:FlightPlan
 * BeginFeature:Ticket
 * @property Ticket[] $tickets
 * EndFeature:Ticket
 * BeginFeature:Line
 * @property Line $idLine
 * EndFeature:Line
 * BeginFeature:Vehicle
 * @property Vehicle $idVehicle
 * EndFeature:Vehicle
 */
abstract class BaseTravel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'travel';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Travel|Travels', $n);
	}

	public static function representingColumn() {
		return 'start_date';
	}

	public function rules() {
		return array(
			array(
			/* BeginFeature:Line */
			'id_line, '.
			/* EndFeature:Line */
			
			/* BeginFeature:Vehicle */
			'id_vehicle, '.
			/* EndFeature:Vehicle */
			'start_date, end_date', 'required'),
			array(
			/* BeginFeature:Line */
			'id_line, '.
			/* EndFeature:Line */
			'id_vehicle', 'numerical', 'integerOnly'=>true),
			array('id, '.
			/* BeginFeature:Line */
			'id_line, '.
			/* EndFeature:Line */
			
			/* BeginFeature:Vehicle */
			'id_vehicle, '.
			/* EndFeature:Vehicle */
			'start_date, end_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
            		/* BeginFeature:FlightPlan */
			'flightPlans' => array(self::HAS_MANY, 'FlightPlan', 'id_travel'),
            		/* EndFeature:FlightPlan */
            		/* BeginFeature:Ticket */
			'tickets' => array(self::HAS_MANY, 'Ticket', 'id_travel'),
            		/* EndFeature:Ticket */
            		/* BeginFeature:Line */
			'idLine' => array(self::BELONGS_TO, 'Line', 'id_line'),
            		/* EndFeature:Line */
            		/* BeginFeature:Vehicle */
			'idVehicle' => array(self::BELONGS_TO, 'Vehicle', 'id_vehicle'),
            		/* EndFeature:Vehicle */
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			/* BeginFeature:Line */
			'id_line' => null,
			/* EndFeature:Line */
			/* BeginFeature:Vehicle */
			'id_vehicle' => null,
			/* EndFeature:Vehicle */
			'start_date' => Yii::t('app', 'Start Date'),
			'end_date' => Yii::t('app', 'End Date'),
			/* BeginFeature:FlightPlan */
			'flightPlans' => null,
			/* EndFeature:FlightPlan */
			/* BeginFeature:Ticket */
			'tickets' => null,
			/* EndFeature:Ticket */
			/* BeginFeature:Line */
			'idLine' => null,
			/* EndFeature:Line */
			/* BeginFeature:Vehicle */
			'idVehicle' => null,
			/* EndFeature:Vehicle */
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		/* BeginFeature:Line */
		$criteria->compare('id_line', $this->id_line);
		/* EndFeature:Line */
		/* BeginFeature:Vehicle */
		$criteria->compare('id_vehicle', $this->id_vehicle);
		/* EndFeature:Vehicle */
		$criteria->compare('start_date', $this->start_date, true);
		$criteria->compare('end_date', $this->end_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
/* EndFeature:Travel */