<?php /* BeginFeature:State */
/**
 * This is the model base class for the table "state".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "State".
 *
 * Columns in table "state" available as properties of the model,
 * followed by relations of table "state" available as properties of the model.
 *
 * @property integer $id    
 * BeginFeature:Country    
 * @property integer $id_country
 * EndFeature:Country    
 * @property string $code    
 * @property string $name    
 *
 * BeginFeature:City
 * @property City[] $cities
 * EndFeature:City
 * BeginFeature:Country
 * @property Country $idCountry
 * EndFeature:Country
 */
abstract class BaseState extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'state';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'State|States', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array(
			/* BeginFeature:Country */
			'id_country, '.
			/* EndFeature:Country */
			'code, name', 'required'),
			array('id_country', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>2),
			array('name', 'length', 'max'=>45),
			array('id, id_country, code, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
            		/* BeginFeature:City */
			'cities' => array(self::HAS_MANY, 'City', 'id_state'),
            		/* EndFeature:City */
            		/* BeginFeature:Country */
			'idCountry' => array(self::BELONGS_TO, 'Country', 'id_country'),
            		/* EndFeature:Country */
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			/* BeginFeature:Country */
			'id_country' => null,
			/* EndFeature:Country */
			'code' => Yii::t('app', 'Code'),
			'name' => Yii::t('app', 'Name'),
			/* BeginFeature:City */
			'cities' => null,
			/* EndFeature:City */
			/* BeginFeature:Country */
			'idCountry' => null,
			/* EndFeature:Country */
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		/* BeginFeature:Country */
		$criteria->compare('id_country', $this->id_country);
		/* EndFeature:Country */
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
/* EndFeature:State */