<?php /* BeginFeature:Vehicle */
/**
 * This is the model base class for the table "vehicle".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Vehicle".
 *
 * Columns in table "vehicle" available as properties of the model,
 * followed by relations of table "vehicle" available as properties of the model.
 *
 * @property integer $id    
 * @property string $code    
 * BeginFeature:VehicleType    
 * @property integer $id_vehicle_type
 * EndFeature:VehicleType    
 * BeginFeature:VehicleModel    
 * @property integer $id_vehicle_model
 * EndFeature:VehicleModel    
 * @property integer $capacity    
 * @property integer $active    
 *
 * BeginFeature:Travel
 * @property Travel[] $travels
 * EndFeature:Travel
 * BeginFeature:VehicleModel
 * @property VehicleModel $idVehicleModel
 * EndFeature:VehicleModel
 * BeginFeature:VehicleType
 * @property VehicleType $idVehicleType
 * EndFeature:VehicleType
 * BeginFeature:VehicleSeat
 * @property VehicleSeat[] $vehicleSeats
 * EndFeature:VehicleSeat
 */
abstract class BaseVehicle extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vehicle';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Vehicle|Vehicles', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code, '.
			/* BeginFeature:VehicleType */
			'id_vehicle_type, '.
			/* EndFeature:VehicleType */
			
			/* BeginFeature:VehicleModel */
			'id_vehicle_model, '.
			/* EndFeature:VehicleModel */
			'capacity', 'required'),
			array(
			/* BeginFeature:VehicleType */
			'id_vehicle_type, '.
			/* EndFeature:VehicleType */
			
			/* BeginFeature:VehicleModel */
			'id_vehicle_model, '.
			/* EndFeature:VehicleModel */
			'capacity, active', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>45),
			array('active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, '.
			/* BeginFeature:VehicleType */
			'id_vehicle_type, '.
			/* EndFeature:VehicleType */
			
			/* BeginFeature:VehicleModel */
			'id_vehicle_model, '.
			/* EndFeature:VehicleModel */
			'capacity, active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
            		/* BeginFeature:Travel */
			'travels' => array(self::HAS_MANY, 'Travel', 'id_vehicle'),
            		/* EndFeature:Travel */
            		/* BeginFeature:VehicleModel */
			'idVehicleModel' => array(self::BELONGS_TO, 'VehicleModel', 'id_vehicle_model'),
            		/* EndFeature:VehicleModel */
            		/* BeginFeature:VehicleType */
			'idVehicleType' => array(self::BELONGS_TO, 'VehicleType', 'id_vehicle_type'),
            		/* EndFeature:VehicleType */
            		/* BeginFeature:VehicleSeat */
			'vehicleSeats' => array(self::HAS_MANY, 'VehicleSeat', 'id_vehicle'),
            		/* EndFeature:VehicleSeat */
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			/* BeginFeature:VehicleType */
			'id_vehicle_type' => null,
			/* EndFeature:VehicleType */
			/* BeginFeature:VehicleModel */
			'id_vehicle_model' => null,
			/* EndFeature:VehicleModel */
			'capacity' => Yii::t('app', 'Capacity'),
			'active' => Yii::t('app', 'Active'),
			/* BeginFeature:Travel */
			'travels' => null,
			/* EndFeature:Travel */
			/* BeginFeature:VehicleModel */
			'idVehicleModel' => null,
			/* EndFeature:VehicleModel */
			/* BeginFeature:VehicleType */
			'idVehicleType' => null,
			/* EndFeature:VehicleType */
			/* BeginFeature:VehicleSeat */
			'vehicleSeats' => null,
			/* EndFeature:VehicleSeat */
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		/* BeginFeature:VehicleType */
		$criteria->compare('id_vehicle_type', $this->id_vehicle_type);
		/* EndFeature:VehicleType */
		/* BeginFeature:VehicleModel */
		$criteria->compare('id_vehicle_model', $this->id_vehicle_model);
		/* EndFeature:VehicleModel */
		$criteria->compare('capacity', $this->capacity);
		$criteria->compare('active', $this->active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
/* EndFeature:Vehicle */