<?php
/**
 * This is the model base class for the table "segment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Segment".
 *
 * Columns in table "segment" available as properties of the model,
 * followed by relations of table "segment" available as properties of the model.
 *
 * @property integer $id    
 * BeginFeature:Line    
 * @property integer $id_line
 * EndFeature:Line    
 * BeginFeature:Station    
 * @property integer $id_station_departure
 * EndFeature:Station    
 * BeginFeature:Station    
 * @property integer $id_station_arrival
 * EndFeature:Station    
 * @property integer $sequence_number    
 * @property string $estimated_time    
 *
 * BeginFeature:Line
 * @property Line $idLine
 * EndFeature:Line
 * BeginFeature:Station
 * @property Station $idStationArrival
 * EndFeature:Station
 * BeginFeature:Station
 * @property Station $idStationDeparture
 * EndFeature:Station
 * BeginFeature:TicketSegment
 * @property TicketSegment[] $ticketSegments
 * EndFeature:TicketSegment
 */
abstract class BaseSegment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'segment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Segment|Segments', $n);
	}

	public static function representingColumn() {
		return 'estimated_time';
	}

	public function rules() {
		return array(
			array(
			/* BeginFeature:Line */
			'id_line, '.
			/* EndFeature:Line */
			
			/* BeginFeature:Station */
			'id_station_departure, '.
			/* EndFeature:Station */
			
			/* BeginFeature:Station */
			'id_station_arrival, '.
			/* EndFeature:Station */
			'sequence_number', 'required'),
			array(
			/* BeginFeature:Line */
			'id_line, '.
			/* EndFeature:Line */
			
			/* BeginFeature:Station */
			'id_station_departure, '.
			/* EndFeature:Station */
			
			/* BeginFeature:Station */
			'id_station_arrival, '.
			/* EndFeature:Station */
			'sequence_number', 'numerical', 'integerOnly'=>true),
			array('estimated_time', 'safe'),
			array('estimated_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, '.
			/* BeginFeature:Line */
			'id_line, '.
			/* EndFeature:Line */
			
			/* BeginFeature:Station */
			'id_station_departure, '.
			/* EndFeature:Station */
			
			/* BeginFeature:Station */
			'id_station_arrival, '.
			/* EndFeature:Station */
			'sequence_number, estimated_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
            		/* BeginFeature:Line */
			'idLine' => array(self::BELONGS_TO, 'Line', 'id_line'),
            		/* EndFeature:Line */
            		/* BeginFeature:Station */
			'idStationArrival' => array(self::BELONGS_TO, 'Station', 'id_station_arrival'),
            		/* EndFeature:Station */
            		/* BeginFeature:Station */
			'idStationDeparture' => array(self::BELONGS_TO, 'Station', 'id_station_departure'),
            		/* EndFeature:Station */
            		/* BeginFeature:TicketSegment */
			'ticketSegments' => array(self::HAS_MANY, 'TicketSegment', 'id_segment'),
            		/* EndFeature:TicketSegment */
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			/* BeginFeature:Line */
			'id_line' => null,
			/* EndFeature:Line */
			/* BeginFeature:Station */
			'id_station_departure' => null,
			/* EndFeature:Station */
			/* BeginFeature:Station */
			'id_station_arrival' => null,
			/* EndFeature:Station */
			'sequence_number' => Yii::t('app', 'Sequence Number'),
			'estimated_time' => Yii::t('app', 'Estimated Time'),
			/* BeginFeature:Line */
			'idLine' => null,
			/* EndFeature:Line */
			/* BeginFeature:Station */
			'idStationArrival' => null,
			/* EndFeature:Station */
			/* BeginFeature:Station */
			'idStationDeparture' => null,
			/* EndFeature:Station */
			/* BeginFeature:TicketSegment */
			'ticketSegments' => null,
			/* EndFeature:TicketSegment */
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		/* BeginFeature:Line */
		$criteria->compare('id_line', $this->id_line);
		/* EndFeature:Line */
		/* BeginFeature:Station */
		$criteria->compare('id_station_departure', $this->id_station_departure);
		/* EndFeature:Station */
		/* BeginFeature:Station */
		$criteria->compare('id_station_arrival', $this->id_station_arrival);
		/* EndFeature:Station */
		$criteria->compare('sequence_number', $this->sequence_number);
		$criteria->compare('estimated_time', $this->estimated_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
