<?php /* BeginFeature:VehicleModel */
/**
 * This is the model base class for the table "vehicle_model".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VehicleModel".
 *
 * Columns in table "vehicle_model" available as properties of the model,
 * followed by relations of table "vehicle_model" available as properties of the model.
 *
 * @property integer $id    
 * BeginFeature:Manufacturer    
 * @property integer $id_manufactorer
 * EndFeature:Manufacturer    
 * @property string $name    
 * @property integer $active    
 *
 * BeginFeature:Vehicle
 * @property Vehicle[] $vehicles
 * EndFeature:Vehicle
 * BeginFeature:Manufacturer
 * @property Manufacturer $idManufactorer
 * EndFeature:Manufacturer
 */
abstract class BaseVehicleModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vehicle_model';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VehicleModel|VehicleModels', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array(
			/* BeginFeature:Manufacturer */
			'id_manufactorer, '.
			/* EndFeature:Manufacturer */
			'name', 'required'),
			array(
			/* BeginFeature:Manufacturer */
			'id_manufactorer, '.
			/* EndFeature:Manufacturer */
			'active', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>45),
			array('active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, id_manufactorer, name, active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
            		/* BeginFeature:Vehicle */
			'vehicles' => array(self::HAS_MANY, 'Vehicle', 'id_vehicle_model'),
            		/* EndFeature:Vehicle */
            		/* BeginFeature:Manufacturer */
			'idManufactorer' => array(self::BELONGS_TO, 'Manufacturer', 'id_manufactorer'),
            		/* EndFeature:Manufacturer */
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			/* BeginFeature:Manufacturer */
			'id_manufactorer' => null,
			/* EndFeature:Manufacturer */
			'name' => Yii::t('app', 'Name'),
			'active' => Yii::t('app', 'Active'),
			/* BeginFeature:Vehicle */
			'vehicles' => null,
			/* EndFeature:Vehicle */
			/* BeginFeature:Manufacturer */
			'idManufactorer' => null,
			/* EndFeature:Manufacturer */
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		/* BeginFeature:Manufacturer */
		$criteria->compare('id_manufactorer', $this->id_manufactorer);
		/* EndFeature:Manufacturer */
		$criteria->compare('name', $this->name, true);
		$criteria->compare('active', $this->active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
/* EndFeature:VehicleModel */