<?php /* BeginFeature:FlightPlan */
/**
 * This is the model base class for the table "flight_plan".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FlightPlan".
 *
 * Columns in table "flight_plan" available as properties of the model,
 * followed by relations of table "flight_plan" available as properties of the model.
 *
 * @property integer $id    
 * BeginFeature:Travel    
 * @property integer $id_travel
 * EndFeature:Travel    
 * BeginFeature:Station    
 * @property integer $id_station_alternative_airport
 * EndFeature:Station    
 * @property string $type    
 * @property string $route    
 * @property string $pilot_name    
 * @property string $pilot_contact    
 * @property string $fuel_on_board    
 *
 * BeginFeature:Station
 * @property Station $idStationAlternativeAirport
 * EndFeature:Station
 * BeginFeature:Travel
 * @property Travel $idTravel
 * EndFeature:Travel
 */
abstract class BaseFlightPlan extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'flight_plan';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Flight Plan|Flight Plans', $n);
	}

	public static function representingColumn() {
		return 'type';
	}

	public function rules() {
		return array(
			array(
			/* BeginFeature:Travel */
			'id_travel, '.
			/* EndFeature:Travel */
			
			/* BeginFeature:Station */
			'id_station_alternative_airport, '.
			/* EndFeature:Station */
			'type, route, pilot_name, pilot_contact, fuel_on_board', 'required'),
			array(
			/* BeginFeature:Travel */
			'id_travel, '.
			/* EndFeature:Travel */
			'id_station_alternative_airport', 'numerical', 'integerOnly'=>true),
			array('type, route, pilot_name, pilot_contact', 'length', 'max'=>45),
			array('id, '.
			/* BeginFeature:Travel */
			'id_travel, '.
			/* EndFeature:Travel */
			
			/* BeginFeature:Station */
			'id_station_alternative_airport, '.
			/* EndFeature:Station */
			'type, route, pilot_name, pilot_contact, fuel_on_board', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
            		/* BeginFeature:Station */
			'idStationAlternativeAirport' => array(self::BELONGS_TO, 'Station', 'id_station_alternative_airport'),
            		/* EndFeature:Station */
            		/* BeginFeature:Travel */
			'idTravel' => array(self::BELONGS_TO, 'Travel', 'id_travel'),
            		/* EndFeature:Travel */
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			/* BeginFeature:Travel */
			'id_travel' => null,
			/* EndFeature:Travel */
			/* BeginFeature:Station */
			'id_station_alternative_airport' => 'Alternative Airport',
			/* EndFeature:Station */
			'type' => Yii::t('app', 'Type'),
			'route' => Yii::t('app', 'Route'),
			'pilot_name' => Yii::t('app', 'Pilot Name'),
			'pilot_contact' => Yii::t('app', 'Pilot Contact'),
			'fuel_on_board' => Yii::t('app', 'Fuel On Board'),
			/* BeginFeature:Station */
			'idStationAlternativeAirport' => 'Alternative Airport',
			/* EndFeature:Station */
			/* BeginFeature:Travel */
			'idTravel' => null,
			/* EndFeature:Travel */
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		/* BeginFeature:Travel */
		$criteria->compare('id_travel', $this->id_travel);
		/* EndFeature:Travel */
		/* BeginFeature:Station */
		$criteria->compare('id_station_alternative_airport', $this->id_station_alternative_airport);
		/* EndFeature:Station */
		$criteria->compare('type', $this->type, true);
		$criteria->compare('route', $this->route, true);
		$criteria->compare('pilot_name', $this->pilot_name, true);
		$criteria->compare('pilot_contact', $this->pilot_contact, true);
		$criteria->compare('fuel_on_board', $this->fuel_on_board, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
/* EndFeature:FlightPlan */