<?php /* BeginFeature:SeatType */
/**
 * This is the model base class for the table "seat_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SeatType".
 *
 * Columns in table "seat_type" available as properties of the model,
 * followed by relations of table "seat_type" available as properties of the model.
 *
 * @property integer $id_seat_type    
 * @property string $name    
 * @property integer $active    
 *
 * BeginFeature:VehicleSeat
 * @property VehicleSeat[] $vehicleSeats
 * EndFeature:VehicleSeat
 */
abstract class BaseSeatType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'seat_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Seat Type|Seat Types', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('active', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>45),
			array('active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_seat_type, name, active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
            		/* BeginFeature:VehicleSeat */
			'vehicleSeats' => array(self::HAS_MANY, 'VehicleSeat', 'id_seat_type'),
            		/* EndFeature:VehicleSeat */
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_seat_type' => Yii::t('app', 'Id Seat Type'),
			'name' => Yii::t('app', 'Name'),
			'active' => Yii::t('app', 'Active'),
			/* BeginFeature:VehicleSeat */
			'vehicleSeats' => null,
			/* EndFeature:VehicleSeat */
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_seat_type', $this->id_seat_type);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('active', $this->active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
/* EndFeature:SeatType */