<?php /* BeginFeature:VehicleType */
/**
 * This is the model base class for the table "vehicle_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VehicleType".
 *
 * Columns in table "vehicle_type" available as properties of the model,
 * followed by relations of table "vehicle_type" available as properties of the model.
 *
 * @property integer $id    
 * @property string $name    
 * @property string $description    
 *
 * BeginFeature:Station
 * @property Station[] $stations
 * EndFeature:Station
 * BeginFeature:Vehicle
 * @property Vehicle[] $vehicles
 * EndFeature:Vehicle
 */
abstract class BaseVehicleType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vehicle_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Vehicle Type|Vehicle Types', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>45),
			array('description', 'length', 'max'=>255),
			array('description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
            		/* BeginFeature:Station */
			'stations' => array(self::HAS_MANY, 'Station', 'id_vehicle_type'),
            		/* EndFeature:Station */
            		/* BeginFeature:Vehicle */
			'vehicles' => array(self::HAS_MANY, 'Vehicle', 'id_vehicle_type'),
            		/* EndFeature:Vehicle */
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			/* BeginFeature:Station */
			'stations' => null,
			/* EndFeature:Station */
			/* BeginFeature:Vehicle */
			'vehicles' => null,
			/* EndFeature:Vehicle */
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
/* EndFeature:VehicleType */